//go:build (linux && cgo) || (darwin && cgo) || (freebsd && cgo)

package patching_sys

import (
	"plugin"
	"unsafe"
)

//============================================================================
// copy from runtime/plugin.go
//============================================================================

/*
   #cgo linux LDFLAGS: -ldl
   #include <dlfcn.h>
   #include <limits.h>
   #include <stdlib.h>
   #include <stdint.h>
   #include <stdio.h>

   static void* pluginOpen(const char* path, char** err) {
   	void* h = dlopen(path, RTLD_NOW|RTLD_GLOBAL);
   	if (h == NULL) {
   		*err = (char*)dlerror();
   	}
   	return h;
   }
*/
import "C"

//go:linkname firstmoduledata runtime.firstmoduledata
var firstmoduledata moduledata

type modulehash struct {
	modulename   string
	linktimehash string
	runtimehash  *string
}

type textsect struct {
	vaddr    uintptr // prelinked section vaddr
	end      uintptr // vaddr + section length
	baseaddr uintptr // relocated section address
}

type functab struct {
	entryoff uint32 // relative to runtime.text
	funcoff  uint32
}

// A ptabEntry is generated by the compiler for each exported function
// and global variable in the main package of a plugin. It is used to
// initialize the plugin module's symbol map.
type ptabEntry struct {
	name uint32
	typ  uint32
}

type bitvector struct {
	n        int32 // # of bits
	bytedata *uint8
}

type moduledata struct {
	pcHeader     uintptr
	funcnametab  []byte
	cutab        []uint32
	filetab      []byte
	pctab        []byte
	pclntable    []byte
	ftab         []functab
	findfunctab  uintptr
	minpc, maxpc uintptr

	text, etext           uintptr
	noptrdata, enoptrdata uintptr
	data, edata           uintptr
	bss, ebss             uintptr
	noptrbss, enoptrbss   uintptr
	covctrs, ecovctrs     uintptr
	end, gcdata, gcbss    uintptr
	types, etypes         uintptr
	rodata                uintptr
	gofunc                uintptr // go.func.*

	textsectmap []textsect
	typelinks   []int32 // offsets from types
	itablinks   []uintptr

	ptab []ptabEntry

	pluginpath string
	pkghashes  []modulehash

	modulename   string
	modulehashes []modulehash

	hasmain uint8 // 1 if module contains the main function, 0 otherwise

	gcdatamask, gcbssmask bitvector

	typemap map[uintptr]uintptr // offset to *_rtype in previous module

	bad bool // module failed to load and should be ignored

	next *moduledata
}

// Plugin is a loaded Go plugin.
type Plugin struct {
	pluginpath string
	err        string        // set if plugin failed to load
	loaded     chan struct{} // closed when loaded
}

func bypassPkgHashCheck(name string) {
	cPath := make([]byte, C.PATH_MAX+1)
	cRelName := make([]byte, len(name)+1)
	copy(cRelName, name)
	if C.realpath(
		(*C.char)(unsafe.Pointer(&cRelName[0])),
		(*C.char)(unsafe.Pointer(&cPath[0]))) == nil {
		return
	}

	var cErr *C.char
	C.pluginOpen((*C.char)(unsafe.Pointer(&cPath[0])), &cErr)
	if cErr != nil {
		return
	}
	md := firstmoduledata.next
	for pmd := firstmoduledata.next; pmd != nil; pmd = pmd.next {
		if pmd.bad {
			md = nil // we only want the last module
			continue
		}
		md = pmd
	}
	newhash := make([]modulehash, 0, len(md.pkghashes))
	for _, pkghash := range md.pkghashes {
		pkghash.linktimehash = *pkghash.runtimehash
		newhash = append(newhash, pkghash)
	}
	md.pkghashes = newhash
}

func unload(p *plugin.Plugin) {
	imp := (*Plugin)(unsafe.Pointer(p))
	md := firstmoduledata.next
	for pmd := firstmoduledata.next; pmd != nil; pmd = pmd.next {
		if pmd.bad {
			md = nil // we only want the last module
			continue
		}
		md = pmd
		if md.pluginpath == imp.pluginpath {
			md.pluginpath = ""
			return
		}
	}
}
